---

default: -p pretty #-p html

pretty: --format pretty
#html: --format html --out=report/relatorio.html



#Projeto do Luciano

#default: --no-source --color --format pretty
#hlg: ENV="hlg" debug=false
#local: ENV="prod" debug=false
#prd: ENV="prd" debug=false
